version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: MyRoomServer/Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:?}
    ports:
      - "${DEPLOY_PORT}:80"
    restart: always
